-- ============================================================================
-- Book #13: Semiconductor Fab Economics & Capital Allocation
-- Database Updates for CFS (MariaDB) and AMEM (PostgreSQL)
-- ============================================================================

INSERT INTO qa_responses (keyword, book_title, book_number, section, canonical_url, summary, last_updated) VALUES
('fab economics', 'Semiconductor Fab Economics', 13, 'Chapter 1: The Anatomy of a $20 Billion GigaFab', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/01-the-20-billion-dollar-giga-fab.md', 'Semiconductor fab economics: Capital allocation framework governing $20B+ GigaFabs, where WFE tools represent 75-80% of capex and 5-year straight-line depreciation creates massive cash flow compounding.', NOW()),
('depreciation moat', 'Semiconductor Fab Economics', 13, 'Chapter 2: Depreciation Schedules & Cash Flow Moats', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/02-depreciation-schedules-cash-flow-moats.md', 'Depreciation cash flow moat: Accounting depreciation expires after 5 years, allowing fully depreciated mega-fabs to produce trailing-edge wafers for 15-20+ years with >60% operating margins.', NOW()),
('wafer pricing', 'Semiconductor Fab Economics', 13, 'Chapter 3: Wafer Pricing Models & Die Cost', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/03-wafer-pricing-die-cost-economics.md', 'Wafer pricing economics: Escalating wafer ASPs ($3,000 at 28nm to $25,000+ at 2nm) balanced by De Vries net good dies per wafer and exponential yield sensitivity in large-die AI chips.', NOW()),
('operational leverage', 'Semiconductor Fab Economics', 13, 'Chapter 4: Capacity Utilization & Operational Leverage', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/04-capacity-utilization-operational-leverage.md', 'Operational leverage in fabs: Fixed overhead (75-85% of total costs) creates immense elasticity, where operating above 95% capacity utilization generates >80% marginal contribution margins.', NOW()),
('AMHS', 'Semiconductor Fab Economics', 13, 'Chapter 5: Cleanroom Logistics & AMHS', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/05-cleanroom-logistics-automated-material-handling.md', 'Automated Material Handling System (AMHS): High-speed ceiling-mounted Overhead Hoist Transport (OHT) vehicles routing 25-wafer FOUPs across automated tool bays to minimize Little''s Law cycle times.', NOW()),
('WFE duopoly', 'Semiconductor Fab Economics', 13, 'Chapter 6: Equipment Supplier Duopolies', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/06-equipment-vendor-duopoly-pricing-power.md', 'WFE pricing power: Equipment oligopoly (ASML, Lam, AMAT, TEL, KLA) capturing 45-55% gross margins and recurring service annuities from high fab switching costs.', NOW()),
('CHIPS Act', 'Semiconductor Fab Economics', 13, 'Chapter 7: Geopolitical Subsidies', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/07-geopolitical-fab-subsidies-chips-acts.md', 'Geopolitical fab economics: Government manufacturing grants bridging the 3-4x construction capex and 20-30% unit op-ex cost disadvantage of onshore US/European wafer fabs.', NOW()),
('capital allocation lattice', 'Semiconductor Fab Economics', 13, 'Chapter 8: The Ultimate Capital Allocation Lattice', 'https://github.com/chipfoundryservices/ebook-fab-economics/blob/main/chapters/08-the-ultimate-capital-allocation-lattice.md', 'Capital allocation lattice: first-principles inversion framework ranking semiconductor ROIC moats: Equipment Monopolies (30-42%) > Pure-Play Foundry (20-26%) > Sub-Scale IDMs (5-12%).', NOW());
